// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file contains the Genkit flow for generating AI-powered hashtags for social media posts.
 *
 * It allows artisans to increase the visibility of their posts and reach a larger audience.
 *
 * @module ai/flows/ai-generated-hashtags
 *
 * @exports generateHashtags - An async function that takes craft details and generates relevant hashtags.
 * @exports GenerateHashtagsInput - The input type for the generateHashtags function.
 * @exports GenerateHashtagsOutput - The output type for the generateHashtags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for generating hashtags. Requires a craft description and an optional image.
 */
const GenerateHashtagsInputSchema = z.object({
  craftDescription: z
    .string()
    .describe('A detailed description of the craft, including its materials, techniques, and unique features.'),
  craftPhotoDataUri: z
    .string()
    .optional()
    .describe(
      "A photo of the craft, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});

export type GenerateHashtagsInput = z.infer<typeof GenerateHashtagsInputSchema>;

/**
 * Output schema for the generated hashtags.
 */
const GenerateHashtagsOutputSchema = z.object({
  hashtags: z
    .array(z.string())
    .describe('An array of relevant and trending hashtags to increase visibility.'),
});

export type GenerateHashtagsOutput = z.infer<typeof GenerateHashtagsOutputSchema>;

/**
 * Async function to generate hashtags for a given craft description and optional image.
 * @param {GenerateHashtagsInput} input - The input object containing craft details.
 * @returns {Promise<GenerateHashtagsOutput>} - A promise resolving to an object containing an array of hashtags.
 */
export async function generateHashtags(input: GenerateHashtagsInput): Promise<GenerateHashtagsOutput> {
  return generateHashtagsFlow(input);
}

/**
 * Prompt definition for generating hashtags based on the craft description and optional image.
 */
const generateHashtagsPrompt = ai.definePrompt({
  name: 'generateHashtagsPrompt',
  input: {schema: GenerateHashtagsInputSchema},
  output: {schema: GenerateHashtagsOutputSchema},
  prompt: `You are an AI social media assistant for artisans who create handcrafted items. Your task is to generate a list of relevant and trending hashtags that will increase the visibility of their posts on social media.

  Consider the following craft description when generating the hashtags:
  Craft Description: {{{craftDescription}}}
  {{#if craftPhotoDataUri}}
  Craft Photo: {{media url=craftPhotoDataUri}}
  {{/if}}

  Provide a diverse set of hashtags, including broad terms, niche terms, and trending topics related to the craft.  The hashtags should not contain the '#' symbol.
  Format the response as a JSON object with a "hashtags" key containing an array of strings.
  Do not include explanations or introductory phrases, only the JSON object.
  `,
});

/**
 * Genkit flow definition for generating hashtags.
 */
const generateHashtagsFlow = ai.defineFlow(
  {
    name: 'generateHashtagsFlow',
    inputSchema: GenerateHashtagsInputSchema,
    outputSchema: GenerateHashtagsOutputSchema,
  },
  async input => {
    const {output} = await generateHashtagsPrompt(input);
    return output!;
  }
);
